### ISSUE TITLE
ToDo-Liste

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Rustco-Network/ToDo#1]
- [ ] Nick Plugin
- [ ] ChatFilter (Keine Bösen Wörter schreiben können und man wird automatisch aus dem Chat gebannt. Command später)
- [ ] HackDetection (Detectet KillAura, Forcefield etc.)
- [ ] AntiCheat (Man kann andere Hacks auch nicht benutzen)
- [ ] Spam Filter (Man kann nicht spammen)

**Comment by ThexXTURBOXx** [comment]
Hab das mal in einzelne Issues geschrieben
